import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "@/styles/globals.css";
import TransitionProvider from "@/components/TransitionProvider";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { Providers } from "@/lib/providers";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className={`${spaceGrotesk.className} min-h-full flex flex-col`}>
        <Providers>
          <TransitionProvider>
            <Navbar />
            {children}
            <Footer />
          </TransitionProvider>
        </Providers>
      </body>
    </html>
  );
}
